import Head from 'next/head';
import Image from 'next/image';
import {useEffect, useState} from "react";

import LinkComponent from '@/components/LinkComponent'
import linkData from '@/fillData/linkData'
import profileData from '@/fillData/profileData'

import "animate.css";
import { handleAnimation } from '@/animation'


export default function Home() {

  const data = linkData;
  const profileImageSrc = "/profileImage/" + profileData.profileImage;
  const name = profileData.name ? profileData.name : undefined;
  const logo = profileData.logo ? "/logo/" + profileData.logo : undefined;
  const text = profileData.text;
  const background = profileData.background ? "/background/" + profileData.background : undefined;

  const [mainOverflow, setMainOverflow] = useState<boolean>();
  
  const getHeight = () => {
      let main = document.getElementById("main");
      let height = (main as HTMLElement).offsetHeight;
      let vpHeight = window.innerHeight;
      let vp90 = vpHeight * 0.9;

      let overflow;
      if (height > vp90) {
        overflow = true;
      } else {
        overflow = false;
      }
      overflow ? setMainOverflow(true) : setMainOverflow(false);

      let next = document.getElementById("__next");
      overflow ? (next as HTMLElement).classList.add("overflow") : (next as HTMLElement).classList.remove("overflow");
    }

  useEffect(() => {
    window.addEventListener("resize", getHeight);
    getHeight()
  });


  return (
    <>
      <Head>
        <title>Embla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`animate__animated animate__bounceInDown ${mainOverflow ? "overflow" : ""}`} id="main">
        <div className="image-container" id="profileImageContainer">
          <Image
            id="profileImage"
            src={profileImageSrc}
            alt="Profile Image"
            fill
            sizes="(max-width: 768px) 100vw,
            (max-width: 1200px) 50vw,
            33vw"
            className="animate__animated"
            onMouseEnter={((event) => handleAnimation(event, "animate__swing"))}
          />
        </div>
        {logo ?
            <div className="image-container" id="logoContainer">
              <Image
                src={logo}
                alt="Logo"
                fill
                sizes="(max-width: 768px) 100vw,
                (max-width: 1200px) 50vw,
                33vw"
                id="logoImage"
              />
            </div>
            :
            <h1 id="title">{name}</h1>
        }
        <p id="description">{text}</p>
        <div id="linkContainer">
          {data.map((link, i) => {
            return <LinkComponent key={i} id={"link" + i} link={link.link} text={link.text} renderIcon={link.icon}/>
          })}
        </div>
      </main>
      {background ?
        <div className="image-container" id="backgroundContainer">
          <Image
          src={background}
          alt="Background"
          fill
          id="backgroundImage"
          />
        </div>
      : ""}
      <div id="overlay"></div>
    </>
  )
};

/*
<p>
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
        </p>
        */
